#!/usr/bin/env bash
# Download the pre-built STATIC libduckdb bundle for this platform from GitHub
# releases into .duckdb/ and generate .cargo/config.toml so cargo links it
# statically. DuckDB is never compiled locally and the final otelview binary
# has no runtime dependency on a duckdb dynamic library.
#
# Usage: scripts/fetch-duckdb.sh [version]
# The version must match the libduckdb-sys crate (crate 1.10505.0 ⇒ v1.5.5:
# 1|05|05). Run once before the first cargo build, and again after bumping
# the duckdb crate.
set -euo pipefail

VERSION="${1:-v1.5.5}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/.duckdb"
OS="$(uname -s)"

case "$OS-$(uname -m)" in
  Darwin-arm64)              ASSET="static-libs-osx-arm64.zip" ;;
  Darwin-x86_64)             ASSET="static-libs-osx-amd64.zip" ;;
  Linux-x86_64)              ASSET="static-libs-linux-amd64.zip" ;;
  Linux-aarch64|Linux-arm64) ASSET="static-libs-linux-arm64.zip" ;;
  *) echo "unsupported platform $OS-$(uname -m)" >&2; exit 1 ;;
esac

URL="https://github.com/duckdb/duckdb/releases/download/${VERSION}/${ASSET}"
echo "fetching ${URL}"
rm -rf "$DEST"
mkdir -p "$DEST"
curl -fsSL -o "$DEST/$ASSET" "$URL"
(cd "$DEST" && unzip -oq "$ASSET" && rm "$ASSET")
echo "extracted $(ls "$DEST" | wc -l | tr -d ' ') files to $DEST"

mkdir -p "$ROOT/.cargo"
CONFIG="$ROOT/.cargo/config.toml"
cat > "$CONFIG" <<EOF
# Generated by scripts/fetch-duckdb.sh — links the pre-built STATIC libduckdb
# downloaded from GitHub releases. Re-run the script to regenerate.
# (otelview-storage's build.rs links the bundle's extension archives and the
# C++ runtime when DUCKDB_STATIC=1.)
[env]
DUCKDB_LIB_DIR = "$DEST"
DUCKDB_INCLUDE_DIR = "$DEST"
DUCKDB_STATIC = "1"
EOF
echo "wrote $CONFIG"
echo "static linking configured — the otelview binary will embed DuckDB."
